"""
report_generator.py
--------------------
Bonus - Report Rendering (up to 5 points).

Combines Task 1A + 1B outputs into a one-page Markdown equity research brief,
then renders it as a styled HTML page with an embedded matplotlib chart
(price + SMA50/SMA200 + Bollinger Bands).
"""

from __future__ import annotations

import base64
import io
import logging
import os
from datetime import datetime
from typing import Any, Dict, List

import matplotlib
matplotlib.use("Agg")  # headless rendering, safe for Colab / scripts
import matplotlib.pyplot as plt
import pandas as pd

# BUGFIX (AI-ASSISTED: Claude, claude-sonnet-4-6): the rest of src/ uses
# relative imports (`from . import config`) since this package is invoked as
# `src.report_generator` from main.py / the notebook. Plain `import config`
# / `from schemas import ...` only worked if this file were run standalone
# from inside src/, and raised ModuleNotFoundError otherwise. Date: 2026-09-13
from . import config
from .schemas import AggregatedSentiment, HeadlineSentiment, TradingSignal

logger = logging.getLogger(__name__)

RISK_DISCLAIMER = (
    "**Risk Disclaimer:** This report is generated by an automated research "
    "assistant for educational and demonstration purposes only. It does not "
    "constitute financial advice, a recommendation, or an offer to buy or sell "
    "any security. Technical indicators and LLM-generated sentiment are "
    "backward-looking and can be wrong; past performance is not indicative of "
    "future results. Always consult a licensed financial advisor and conduct "
    "your own due diligence before making investment decisions."
)


def _fmt(value, suffix: str = "", decimals: int = 2) -> str:
    if value is None:
        return "N/A"
    try:
        return f"{value:.{decimals}f}{suffix}"
    except (TypeError, ValueError):
        return str(value)


def build_markdown_report(
    summary: Dict[str, Any],
    aggregated_sentiment: AggregatedSentiment,
    headline_sentiments: List[HeadlineSentiment],
    trading_signal: TradingSignal | None,
) -> str:
    ticker = summary.get("ticker", "UNKNOWN")
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")

    top_three = sorted(headline_sentiments, key=lambda h: h.confidence, reverse=True)[:3]
    top_three_lines = "\n".join(
        f"- **[{h.sentiment.value.upper()}]** {h.headline} _(confidence: {h.confidence:.2f})_ - {h.brief_reason}"
        for h in top_three
    ) or "- No headlines available."

    signal_section = (
        f"**Recommendation: {trading_signal.signal.value}**\n\n{trading_signal.justification}"
        if trading_signal is not None
        else "_LLM signal generation unavailable - check API configuration and logs._"
    )

    md = f"""# Equity Research Brief - {ticker}
_Generated {generated_at}_

## Company Snapshot
| Metric | Value |
|---|---|
| Current Price | {_fmt(summary.get('current_price'), decimals=2)} |
| 52-Week High | {_fmt(summary.get('fifty_two_week_high'), decimals=2)} |
| 52-Week Low | {_fmt(summary.get('fifty_two_week_low'), decimals=2)} |
| P/E Ratio | {_fmt(summary.get('pe_ratio'), decimals=2)} |
| YTD Return | {_fmt(summary.get('ytd_return_pct'), suffix='%', decimals=2)} |

## Technical Outlook
| Indicator | Value |
|---|---|
| SMA-50 | {_fmt(summary.get('sma_50'), decimals=2)} |
| SMA-200 | {_fmt(summary.get('sma_200'), decimals=2)} |
| RSI-14 | {_fmt(summary.get('rsi_14'), decimals=2)} |
| MACD | {_fmt(summary.get('macd'), decimals=3)} |
| MACD Signal | {_fmt(summary.get('macd_signal'), decimals=3)} |
| Bollinger Upper | {_fmt(summary.get('bollinger_upper'), decimals=2)} |
| Bollinger Lower | {_fmt(summary.get('bollinger_lower'), decimals=2)} |
| Rule-Based Momentum | {summary.get('momentum_signal', 'unknown')} |

## News Sentiment Summary
Overall sentiment score: **{aggregated_sentiment.overall_score:+.2f}** ({aggregated_sentiment.overall_label.value})
based on {aggregated_sentiment.headline_count} headlines
({aggregated_sentiment.positive_count} positive / {aggregated_sentiment.neutral_count} neutral / {aggregated_sentiment.negative_count} negative).

**Top 3 headlines by model confidence:**
{top_three_lines}

## LLM Recommendation
{signal_section}

---
{RISK_DISCLAIMER}
"""
    return md


def _render_price_chart_base64(df: pd.DataFrame, ticker: str) -> str:
    """Render a price + SMA + Bollinger Band chart and return it as a base64 PNG string."""
    fig, ax = plt.subplots(figsize=(9, 4.5), dpi=150)

    plot_df = df.tail(252)  # last ~1 trading year for legibility
    ax.plot(plot_df.index, plot_df["Close"], label="Close", linewidth=1.4, color="#1f77b4")

    if "SMA_50" in plot_df.columns:
        ax.plot(plot_df.index, plot_df["SMA_50"], label="SMA 50", linewidth=1.0, color="#ff7f0e")
    if "SMA_200" in plot_df.columns:
        ax.plot(plot_df.index, plot_df["SMA_200"], label="SMA 200", linewidth=1.0, color="#2ca02c")
    if "bb_upper" in plot_df.columns and "bb_lower" in plot_df.columns:
        ax.fill_between(
            plot_df.index, plot_df["bb_lower"], plot_df["bb_upper"],
            color="#7f7f7f", alpha=0.15, label="Bollinger Band (20, 2)"
        )

    ax.set_title(f"{ticker} - Price, Moving Averages & Bollinger Bands (last 12 months)")
    ax.set_xlabel("Date")
    ax.set_ylabel("Price")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def render_html_report(markdown_text: str, df: pd.DataFrame, ticker: str, out_path: str) -> str:
    """Render the markdown brief + an embedded chart as a single styled HTML file."""
    try:
        import markdown as md_lib
        body_html = md_lib.markdown(markdown_text, extensions=["tables"])
    except ImportError:
        logger.warning("`markdown` package not installed - falling back to <pre> block")
        body_html = f"<pre>{markdown_text}</pre>"

    chart_b64 = _render_price_chart_base64(df, ticker) if not df.empty else ""
    chart_html = (
        f'<img src="data:image/png;base64,{chart_b64}" alt="{ticker} price chart" style="max-width:100%;" />'
        if chart_b64
        else "<p><em>Chart unavailable - no price data.</em></p>"
    )

    # BUGFIX (AI-ASSISTED: Claude, claude-sonnet-4-6): styling via `html`/`body`
    # selectors is unreliable when this string is displayed via
    # IPython.display.HTML() - some notebook front-ends insert it as a DOM
    # fragment and strip the <html>/<head>/<body> wrapper tags, so
    # `body { background }` never attaches to anything and the report
    # inherits the host page's (often dark) background behind near-black
    # text. Fix: put background/color/layout on a real <div> (both via a
    # class AND an inline style, so it survives even if the <style> tag
    # itself is stripped by an aggressive sanitizer) instead of relying on
    # body/html selectors. Date: 2026-09-13
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Equity Research Brief - {ticker}</title>
<style>
  .report-container {{
    font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif;
    max-width: 860px;
    margin: 40px auto;
    padding: 20px;
    background: #ffffff;
    color: #1a1a1a;
    line-height: 1.55;
  }}
  .report-container h1, .report-container h2 {{ border-bottom: 1px solid #ddd; padding-bottom: 6px; }}
  .report-container table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
  .report-container th, .report-container td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; color: #1a1a1a; }}
  .report-container th {{ background: #f5f5f5; }}
  .report-container .chart {{ margin: 20px 0; text-align: center; }}
  .report-container .disclaimer {{ background: #fff8e1; border-left: 4px solid #f5a623; padding: 12px 16px; margin-top: 24px; font-size: 0.9em; }}
</style>
</head>
<body>
<div class="report-container" style="background:#ffffff;color:#1a1a1a;font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;max-width:860px;margin:40px auto;padding:20px;line-height:1.55;">
{body_html}
<div class="chart">{chart_html}</div>
</div>
</body>
</html>"""

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path


def save_report(
    summary: Dict[str, Any],
    aggregated_sentiment: AggregatedSentiment,
    headline_sentiments: List[HeadlineSentiment],
    trading_signal: TradingSignal | None,
    df: pd.DataFrame,
) -> Dict[str, str]:
    """Build markdown + HTML report and save both to the output directory."""
    ticker = summary.get("ticker", "UNKNOWN")
    md_text = build_markdown_report(summary, aggregated_sentiment, headline_sentiments, trading_signal)

    md_path = os.path.join(config.OUTPUT_DIR, f"{ticker}_equity_research_brief.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_text)

    html_path = os.path.join(config.OUTPUT_DIR, f"{ticker}_equity_research_brief.html")
    render_html_report(md_text, df, ticker, html_path)

    return {"markdown_path": md_path, "html_path": html_path}